hidden_dim: 128
num_historical_steps: 50
num_future_steps: 60
m2m_layers: 3
a2a_layers: 3
num_map_types: 4
num_mark_types: 16
num_is_inter: 3
num_lane_edge: 6
num_agent_types: 4
num_heads: 8
head_dim: 16
dropout: 0.1
num_modes: 6
output_dim: 2
output_head: true
lr: 0.001
warm_up_epoch: 10
weight_decay: 0.0001
T_max: 60
