predict:
  model:
    hidden_dim: 128
    num_historical_steps: 50
    num_future_steps: 60
    m2m_layers: 3
    a2a_layers: 3
    num_map_types: 4
    num_mark_types: 16
    num_is_inter: 3
    num_lane_edge: 6
    num_agent_types: 4
    num_heads: 8
    head_dim: 16
    dropout: 0.1
    num_modes: 6
    output_dim: 2
    output_head: True
    lr: 1.0e-4
    warm_up_epoch: 2
    weight_decay: 5.0e-5
    T_max: 60

  data:
    data_root: "../argoverse2/VMA"
    train_batch_size: 1
    val_batch_size: 1
    num_historical_steps: 50
    num_future_steps: 60
    a2m_radius: 50
    a2a_radius: 50
    m2m_radius: 150

  accelerator: "auto"
  max_epoch: 60
  device: 1
  gradient_clip_val: 5
  gradient_clip_algorithm: norm